language: node_js
node_js:
- lts/*
addons:
  chrome: stable
notifications:
  email:
    on_success: change
    on_failure: always
script:
- npm run build
- npm run testCoverage
deploy:
  - provider: npm
    email: sandbox_JSUI@coveo.com
    api_key:
      secure: Q5J9xZgaBIlRb/cgEiETnVHA2fK7WS/pE0Iy8E3EZl1WJ4BUdMNiogzKeQKIV0Zhd0jwG3CtcHFCtpZ76sgjn1MPoD8khPIxauj3PMKPgg3QOUwdc+h8DBKYzWLt5ERgjNJIjY0jmzPC3uBEGExViIl3eiRuYe4PhKUbu/kRni9dAR0phCd7saZd72Lj3iSJHE4WRXam5bF3/mg5sMSIVoxbxTcvCXdTmGdpdc9muDo62zJrhVgwD6z7c/enLA69qTyCe7EAvTLldZLxBokJ5T3aZpLKKIDV5X5v6QlxIeidRBGTVhmGQqgLolg1/a0QfEervXMeUlTuxgJMuEbwCK6CGoiAaIie8kagjqAUxpCASMtaXydbe72vTyJvYxc+pYzlmNHWx5zT5ffUh4Gl36cqGwrHlAD85iIe3J6yNCK4kHI3FBBL9cEXBi7RM1pe53Y16muS93CVg1gT8K6u/YxuwBQzDlY2GSjZaDCsBAN3cMoX3qdsVzmY+534F4JYDF/ZJpKcHW1CejrxDIzTtg+HZ5BcU3LAMD/0LYGpfDxRXzhy++NmWKQq6tFb2OdvcroTx0CLjTAuAMuCSCiYNnxog0O8wuwW9xoxss8WxcyjmUh2JN650h/I0xlbZOvEA2rHT9Q/sGmQ8mnOtbxKNhiOIwv1Q9J4qTKCxK/8Xwo=
    on:
      tags: true
      repo: coveo/search-ui-extensions