language: node_js
node_js:
  - lts/*
addons:
  chrome: stable
notifications:
  email:
    on_success: change
    on_failure: always
script:
  - npm run build
  - npm run testCoverage
deploy:
  - provider: npm
    email: sandbox_JSUI@coveo.com
    skip_cleanup: true
    api_key:
      secure: X0u5/OSpsboHSyWqj3V2IjYsdljZAYHrmG6dsE7ZWj8CgEZFtTGpBUZ0GuPd47huGr4Yo5JV2uvA8TJREdXo0gJK4S1/n9CPZHRXTYlF1Qx65RfEFQYaZ9gtsJr5nULbX4C751kQRZl25oX9IKnkPaF+MHyOAs9pD3G5zdsoEj872aF7vkJ9T+fSPtnOMt/P7WRx2CLNvLCqbPHzOc+uDDaT6m0SSVDh1aebSEl4AryCe1zQlvftf8bLo5T7462NScF7k6jDJgUESfSNK9Q6qvW7W7jbFPfo3JIucFm/v0Q4SV2UPjzfD8sEAucKtSBvLwFVYfTREZmle3v7DgdI4iFe8a5ELzohjrq4NzJecy3w3E3DdZcnIE6OpdHaoooW9XMHWAmX5/7CMzbjMxuKNgeA9Xrmmd2Ni9FwFo7KJ4g25rjSa7OnmRmphEyp/jpnF4mXfC5s6sgQI9ZkDB3Pl4giL/3AHKOZLJcq12TbW2/ZS7JRHGo6TpLgMyBWz9uwaPPdjOx6VZi0scP6g0Gy++czauan1KAlkS79fYvgm7upx16qxb6T4CUUqqkD9DQjwBbON8hd6HcVnItIXlTYhpbgABfhQZdSfHGx9ozueEOydyPyO3Ewyl9LyrdweI20Fm5G5Sd93lOvKHSU1wsxTqVEbyRZtfRY6+m0ovlBv4Y=
    on:
      tags: true
      repo: coveo/search-ui-extensions